const { onRequest } = require("firebase-functions/v2/https");
const {setGlobalOptions} = require("firebase-functions/v2");
const { Nuxt } = require("nuxt-start");

const nuxtConfig = require("./nuxt.config.js"); // will be generated by ../predeploy-functions.bat

const nuxt = new Nuxt({
  ...nuxtConfig,
  dev: false,
  buildDir: "nuxt",
});

setGlobalOptions({maxInstances: 10});
exports.ssrapp = onRequest({ timeoutSeconds: 1200, region: ['us-central1']}, async (req, res) => {
  await nuxt.ready();
  nuxt.render(req, res);
});

// const functions = require("firebase-functions");
// exports.ssrappv1 = functions.https.onRequest(async (req, res) => {
//   await nuxt.ready();
//   nuxt.render(req, res);
// });